// Compact airline lookup tables used only as a fallback when the route API
// has no data. Not exhaustive — covers common carriers so the display can show
// an operator name derived from the callsign, and map IATA flight numbers
// (e.g. "AA100") to ICAO callsigns (e.g. "AAL100") for flight tracking.

// ICAO 3-letter callsign prefix -> airline name.
export const AIRLINES = {
  AAL: 'American Airlines',
  ACA: 'Air Canada',
  AFR: 'Air France',
  AMX: 'Aeroméxico',
  ANA: 'All Nippon Airways',
  ASA: 'Alaska Airlines',
  AUA: 'Austrian Airlines',
  AVA: 'Avianca',
  AZU: 'Azul',
  BAW: 'British Airways',
  BEL: 'Brussels Airlines',
  CCA: 'Air China',
  CES: 'China Eastern',
  CPA: 'Cathay Pacific',
  CSN: 'China Southern',
  DAL: 'Delta Air Lines',
  DLH: 'Lufthansa',
  EIN: 'Aer Lingus',
  ELY: 'El Al',
  ETD: 'Etihad Airways',
  EVA: 'EVA Air',
  EZY: 'easyJet',
  FDX: 'FedEx Express',
  FFT: 'Frontier Airlines',
  FIN: 'Finnair',
  GLO: 'Gol',
  HAL: 'Hawaiian Airlines',
  IBE: 'Iberia',
  ICE: 'Icelandair',
  JBU: 'JetBlue',
  JAL: 'Japan Airlines',
  KAL: 'Korean Air',
  KLM: 'KLM',
  LNI: 'Lion Air',
  MAS: 'Malaysia Airlines',
  NKS: 'Spirit Airlines',
  NAX: 'Norwegian',
  QFA: 'Qantas',
  QTR: 'Qatar Airways',
  RYR: 'Ryanair',
  SAS: 'SAS',
  SIA: 'Singapore Airlines',
  SKW: 'SkyWest Airlines',
  SWA: 'Southwest Airlines',
  SWR: 'Swiss',
  TAM: 'LATAM Brasil',
  THY: 'Turkish Airlines',
  UAE: 'Emirates',
  UAL: 'United Airlines',
  UPS: 'UPS Airlines',
  VIR: 'Virgin Atlantic',
  VOI: 'Volaris',
  WJA: 'WestJet',
  WZZ: 'Wizz Air',
};

// IATA 2-char -> ICAO 3-char, for turning flight numbers into search callsigns.
export const IATA2ICAO = {
  AA: 'AAL',
  AC: 'ACA',
  AF: 'AFR',
  AM: 'AMX',
  AS: 'ASA',
  AV: 'AVA',
  AZ: 'ITY',
  B6: 'JBU',
  BA: 'BAW',
  CA: 'CCA',
  CI: 'CAL',
  CX: 'CPA',
  CZ: 'CSN',
  DL: 'DAL',
  EK: 'UAE',
  EY: 'ETD',
  F9: 'FFT',
  FR: 'RYR',
  HA: 'HAL',
  IB: 'IBE',
  JL: 'JAL',
  KE: 'KAL',
  KL: 'KLM',
  LA: 'LAN',
  LH: 'DLH',
  LX: 'SWR',
  MU: 'CES',
  NH: 'ANA',
  NK: 'NKS',
  OS: 'AUA',
  QF: 'QFA',
  QR: 'QTR',
  SK: 'SAS',
  SQ: 'SIA',
  SU: 'AFL',
  TK: 'THY',
  UA: 'UAL',
  VS: 'VIR',
  WN: 'SWA',
  WS: 'WJA',
};
